twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/assets/img': images
    globals:
        # partie originale mis à jour:OK
        pk_live: 'pk_live_518VfvqCka9fpi7fWBGvXrbUI72fmvKwWju9QGFXxfHhvYusOuGP6I1oZ4lgiF23d2uFQkFqvlrYg1Ho54oTvvaXc00hedhXCOl'
